# Generated by Django 5.2.7 on 2025-11-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
